## Numpy Tutorial

In [1]:
import numpy as np

### 1D array

In [2]:
my_list = [1,2,3,4,5]
arr = np.array(my_list)

In [3]:
arr

array([1, 2, 3, 4, 5])

In [4]:
type(arr)

numpy.ndarray

In [8]:
arr.shape

(5,)

### Multidimensional array (2D etc)

In [6]:
my_list1 = [1,2,3,4,5]
my_list2 = [2,4,6,8,10]
my_list3 = [1,3,5,7,9]

m_arr=np.array([my_list1,my_list2,my_list3])

In [7]:
m_arr

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9]])

In [11]:
m_arr.shape 
# This is a 2D array. To visually identify it, 
# it will have 2 opening and closing brakets.

(3, 5)

In [12]:
m_arr.reshape(5,3)
#reshaping an array

array([[ 1,  2,  3],
       [ 4,  5,  2],
       [ 4,  6,  8],
       [10,  1,  3],
       [ 5,  7,  9]])

In [13]:
#While reshaping the total count of numbers should always be same.
# So if it has 15 elements initially, after reshaping also it should be same.
# so (3,5) can be (5,3) or (15,1) or (1,15) but not (5,4) or (4,5) etc etc else we will get ValueError

In [14]:
m_arr.reshape(15,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [ 1],
       [ 3],
       [ 5],
       [ 7],
       [ 9]])

In [15]:
m_arr.reshape(1,15)

array([[ 1,  2,  3,  4,  5,  2,  4,  6,  8, 10,  1,  3,  5,  7,  9]])

### Retreiving values from numpy arrays

In [21]:
# 1D array
arr

array([1, 2, 3, 4, 5])

In [22]:
arr[4]

5

In [23]:
arr[2]

3

In [25]:
# 2D array
m_arr

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9]])

In [26]:
# m_arr[row_start:row_end, col_start:col_end]

In [27]:
m_arr[0:2,0:2]

array([[1, 2],
       [2, 4]])

In [28]:
m_arr[1:,3:]

array([[ 8, 10],
       [ 7,  9]])

### Numpy in-built functions

- arrange
- linspace
- copy() function or broadcasting
- np.ones
- np.random.rand(m,n) where m and n are the rows and colomns to generate a matrix/array of m*n size
- np.random.randn 
- Check other random functions like np.random.randint, np.random.random_sample etc.

### Conditiona operators( < , >, ==, != ) for numpy

In [31]:
m_arr < 4

array([[ True,  True,  True, False, False],
       [ True, False, False, False, False],
       [ True,  True, False, False, False]])

In [32]:
m_arr > 4

array([[False, False, False, False,  True],
       [False, False,  True,  True,  True],
       [False, False,  True,  True,  True]])